AWSTemplateFormatVersion: 2010-09-09

Resources:

  RoleAllowS3:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: allows3ee
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:*"
                Resource: "*"

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0905a3c97561e0b69
      InstanceType: t2.micro
      IamInstanceProfile: !GetAtt RoleAllowS3.Arn
      UserData: |
        sudo apt-get update -y

