name: Build and push docker image

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: login to ecr
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/m8l7i2c5

      - name: build docker image
        run: |
          docker build -t scrapeblade .
      
      - name: tag docker image
        run: |
          docker tag scrapeblade:latest public.ecr.aws/m8l7i2c5/scrapeblade:latest
      
      - name: push docker image
        run: |
          docker push public.ecr.aws/m8l7i2c5/scrapeblade:latest